server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_app
    username: postgres
    password: root@1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect